version: '3'

services:
  postgres-db:
    container_name: db
    image: postgres:13
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  pgadmin:
    container_name: pgadmin6_client
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pass@word123
    ports:
      - 5050:80
  zookeeper:
    image: bitnami/zookeeper:latest
    restart: unless-stopped
    hostname: zookeeper
    ports:
      - '2181:2181'
    volumes:
      - zookeeper:/bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      network:
        ipv4_address: 10.5.0.6
  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    restart: unless-stopped
    hostname: kafka
    ports:
      - '9092:9092'
      - '9093:9093'
    volumes:
      - kafka:/bitnami/kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CLUSTER_ID=test-kafka-cluster
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,INTER_BROKER:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,INTER_BROKER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://localhost:9092,INTER_BROKER://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTER_BROKER
      - KAFKA_CFG_MAX_REQUEST_SIZE=1048576000
    networks:
      network:
        ipv4_address: 10.5.0.5
    depends_on:
      - zookeeper

networks:
  network2:
    driver: bridge
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

volumes:
  postgres-db:
  kafka:
  zookeeper:

